### ISSUE TITLE
Please add Website in "About"

### ISSUE THREAD

**Issue by lzblack** [schen1224/MyPersonalWebsite#1]

**Comment by lzblack** [comment]
Please address this issue.

**Comment by schen1224** [comment]
Hi professor, do you mean by adding an "About" folder?

**Comment by lzblack** [comment]
![image](https://user-images.githubusercontent.com/1173076/199090219-366ebf80-8980-495e-99fe-1ffcc156ecf4.png)

**Comment by schen1224** [comment]
Thank you, Professor! I updated it with my website link.
<img width="338" alt="Screen Shot 2022-10-31 at 3 12 57 PM" src="https://user-images.githubusercontent.com/112512892/199090940-9705db2b-1e4e-46ef-bafa-de2d51f0ff0d.png">
