### ISSUE TITLE
Technical Issue #1

### ISSUE THREAD

**Issue by lilixchiu** [schen1224/MyPersonalWebsite#6]
https://github.com/schen1224/MyPersonalWebsite/blob/7ecfa062e966a5059eee58eb4c1921a80ec2588b/index.html#L9

 <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png" />
  <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png" />

I think you accidentally typed / instead of . for png. Should be image.png

**Comment by schen1224** [comment]
Thank you! I fixed it.
